services:
  Swapi\Enrichment\Component\Connector\Job\JobParameters\ConstraintCollectionProvider\ProductApiImport:
    class: Swapi\Enrichment\Component\Connector\Job\JobParameters\ConstraintCollectionProvider\ProductApiImport
    arguments:
      -
        - 'induxx_api_import'
    tags:
      - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }