services:
  Swapi\Enrichment\Component\Connector\Job\JobParameters\DefaultValueProvider\ProductApiImport:
    class: Swapi\Enrichment\Component\Connector\Job\JobParameters\DefaultValueProvider\ProductApiImport
    arguments:
      -
        - 'induxx_api_import'
    tags:
      - { name: akeneo_batch.job.job_parameters.default_values_provider }