services:
  swapi_connector.job.job_parameters.api_import:
    class: 'Swapi\Enrichment\Component\Connector\Job\JobParameters\ApiImport'
    arguments:
      - '@Swapi\Enrichment\Component\Connector\Job\JobParameters\DefaultValueProvider\ProductApiImport'
      - '@Swapi\Enrichment\Component\Connector\Job\JobParameters\ConstraintCollectionProvider\ProductApiImport'
      -
        - '%swapi_connector.job_name.api_import%'
    tags:
      - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }
      - { name: akeneo_batch.job.job_parameters.default_values_provider }